/* Project Euler, problem 12
 * "The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors? "
 * 
 * answer = 76576500;
 * 76576500 has 576 divisors. but this was found with a brute method
 */


public class Problem012 {
	public static void main(String[] args) {

		int ref = 0;
		for(int i = 1; i < 99999; i++) {
			ref += i;
			if(divisorCount(ref) > 500) {
				System.out.println(ref);
				return;
			}
		}
	}
	
	public static int divisorCount(int n) {
		if(n == 1) {
			return 1;
		}
		int count = Math.sqrt(n) * Math.sqrt(n) == n ? 1 : 2;
		for(int i = 2; i <= Math.ceil(Math.sqrt(n)); i++) {
			if(n % i == 0) {
				count += 2;
			}
		}
		return count;
	}
}
