/* Euler project, problem 2
 * 
 * "Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms." 
 * 
 * answer = 4613732;  //correct
 */

public class Problem002 {
	public static void main(String[] args){
		
		int limit = 4000000;
		int[] fib = new int[] { 1, 1 };
		int answer = 0;
		int i = 0;
		
		while(fib[i] <= limit){
			if(fib[i] % 2 == 0){
				answer += fib[i];
			}
			fib[1 - i] += fib[i];
			i ^= 1;
		}
		System.out.println(answer);
		
	}
}
