import java.util.ArrayList;

/* Project Euler, problem 45
 * 
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * 
 * Triangle	 	 Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 Hn=n(2n-1)	 		1, 6, 15, 28, 45, ....
 * 
 * It can be verified that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 * 
 * answer = 1533776805;  //correct
 */

/*********************************************************
 * new solution
 */

public class Problem045 {
	public static void main(String[] args){

		for (int n = 144; n < 30000; n++) {
			long h = n*(2*n-1);
			if(isTri(h) && isPent(h)){
				System.out.println(n);
				System.out.println("answer: " + h);
				return;
			}
		}
	}
	
	//see problem 44 for explanation
	public static boolean isTri(long num){
		double tmp = (Math.sqrt(1 + 8 * num) - 1.0) / 2.0;
		return tmp == ((int)tmp);
	}

	public static boolean isPent(long num) {
	    double tmp = (Math.sqrt(1 + 24 * num) + 1.0) / 6.0;
	    return tmp == ((int)tmp);
	}
	
}
		
	/*********************************************************
	 * old solution takes forever
	 * 
		
		/*
		ArrayList<Long> t  = new ArrayList<Long>();
		ArrayList<Long> p = new ArrayList<Long>();
		ArrayList<Long> h  = new ArrayList<Long>();
		
		long index = 60000;
		
		for (long i = 1; i <= index; i++) {
			t.add(i * (i + 1) / 2);
			p.add(i * (3 * i - 1) / 2);
			h.add(i * (2 * i - 1));
		}
		for (long i = 286; i < index; i++) {
			if(h.contains(t.get((int)i))
			&& p.contains(t.get((int)i))){
				System.out.println("common: " + t.get((int)i));
				break;
			}
		}
	}
}
*/
