/* Project Euler, problem 12
 * "The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors? "
 * 
 * answer = 76576500;
 * 76576500 has 576 divisors. but this was found with a brute method
 */


public class Problem012 {
	public static void main(String[] args){
		
		int answer = 1;
		int ref = 1;
		
		System.out.println(countFactors(749700));
		
		for (int i = 1; i <= 999999999; i += ref) {
			if(countFactors(i) > countFactors(answer)){
				answer = i;
				System.out.println(i + ", factors: " + countFactors(i));
			}
			if(countFactors(i) > 500){
				System.out.println(i + " over 500 factors");
				break;
			}
			ref++;
		}
	}

	
	
	
	private static int countFactors(int i) {
		int factors = 0;
		for (int a = 1; a <= i; a++) {
			if(i % a == 0){
				factors++;

			}

		}
		return factors;
	}
}
